--- # My first YAML Plybook for Ansible
- hosts: all 
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_vesrion: 0.1b
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: pkg_name
      prompt: install which package
  tasks:
   # - name: Install lynx web broweser
     # action: apt name=lynx state=installed
   # - name: check for telnet client
     # action: apt name=telnet state=absent
    - name: Install Apache web server
      action: apt name=apache2 state=installed
      notify: restart apache2
     # async: 300
    #  poll: 3
   # - name: Install given package 
     # action: apt name={{pkg_name}} state=installed
   #- name: Install nginx
    #  action: apt pkg=nginx state=installed
  handlers:
    - name: restart apache2
      action: service name=apache2 state=restarted
      
 
