--- # apt module example
- hosts: appserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Equivalent of apt-get update
    apt: update_cache=yes
  - name: Equivalent of apt-get upgrade
    apt: upgrade=dist

