--- # AT MODULE EXAMPLE
- hosts: apacheserver
  sudo: yes
  user: deep
  connection: ssh
  gather_facts: no
  tasks:
  - name: Example of a future command with the AT module
    at: command="ls -al /var/log > /home/deep/at.log" count=1 units="minutes"
