--- #Variables at a command line passing example
- hosts: '{{ hosts }}'
  user: '{{ user }}'
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install some software
      apt: pkg={{ pkg }} state=latest
