--- #CRON MODULE EXAMPLE
- hosts: apacheserver
  user: deep
  connection: ssh
#  sudo: yes
  gather_facts: no
  tasks:
  - name: add a CRON job to Test User
#    cron: name="list files" minute="0" hour="1" job="ls -al /etc > /home/deep/cronresult.log"
    cron: name="list files" state=absent
