--- #exercie 3: creating a simple playbook
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Installing lynx on apacheweb
      apt: pkg=lynx state=installed 
    - name: Querying for telnet install
      apt: pkg=telnet state=present

- hosts: appserver
  tasks:
  - name: Installing lynx on appserver
    apt: pkg=lynx state=installed
  - name: Querying telnet install
    apt: pkg=telnet state=present

