--- #error handling example
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Execute a command that will fail
      command: /bin/false
      ignore_errors: yes
    - name: Install telnet
      apt: pkg=telnet state=latest
