--- #FETCH MODULE EXAPLE
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: copy remote hosts file to control server
    fetch: src=/etc/hosts dest=/home/deep/prefix-{{ ansible_hostname }} flat=yes


