--- # file system module
- hosts: appserver
  sudo: yes
  user: deep
  connection: ssh
  gather_facts: no
  tasks:
  - name: Format the remote parttion
    filesystem: fstype=ext3 dev=/dev/xvdf1 opts="-c"

