--- #HTPASSWD module example
- hosts: appserver
  sudo: yes
  user: deep
  connection: ssh
  gather_facts: no
  tasks:
  - name: Install python dependencies
    apt: pkg=python-passlib state=latest
  - name: addin user to web authentication file
    #htpasswd: path=/etc/apache2/.htpasswd name=test2 password=password owner=test2 group=test2 mode=0640
    htpasswd: path=/etc/apache2/.htpasswd name=test2 state=absent
