--- # exercise: playbooks - ignore_errors
- hosts: all
  sudo: yes
  user: deep
  connection: ssh
  gather_facts: no
  tasks:
  - name: install httpd on all servers
    apt: pkg=httpd state=latest
    ignore_errors: yes
  - name: install telnet
    apt: pkg=telnet state=latest


