--- #full include tasks example
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - include: plays/packages.yml
  tasks:
    - name: Verify the telnet is installed
      raw: apt list --installed | grep telnet > /home/deep/pkgs.log
