--- #exercise playbook

- hosts: all
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - include: plays/packages.yml
   - name: verify that package is installed
     raw: apt list --installed | grep lynx > /home/deep/pkg.log

   
