--- # The pause module
- hosts: apacheserver
  sudo: yes
  gather_facts: no
  tasks:
  - name: Install apache2
    action: apt name=apache2 state=installed
  - name: Pausing
    pause:
      #prompt: "Make sure the installation is complete..."
      seconds: 3
  - name: Verify lynx installtion
    action: apt name=lynx state=present
