--- # promt for user package example
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.01b
  vars_prompt:
    - name: pkgtoinstall
      prompt: Install which package?
      default: telnet
      private: no
  tasks:
    - name: Install the indicated package
      apt: pkg={{ pkgtoinstall }} state=latest

