--- #raw module example
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: find the system uptime for the hosts mentioned in this example
    raw: /usr/bin/uptime > uptime.log 
