--- # start at playbook example
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install telnet
      apt: pkg=telnet state=latest
    - name: Install Lynx
      apt: pkg=lynx state=latest
    - name: List Home
      command: ls -al /home/deep
      register: result
    - debug: var=result

