--- #unarchive module example
- hosts: apacheserver
  sudo: yes
  user: deep
  connection: ssh
  gather_facts: no
  tasks:
  - name: unarchiving file from source to destination
    unarchive: src=test.tar.gz dest=/home/deep/unarchive

