--- #until playbook example
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Installing apache web server
      apt: pkg=apache2 state=latest
    - name: verify service status
      shell: systemctl status apache2
      register: result
      until: result.stdout.find("active (running)") != -1
      retries: 5
      delay: 5
    - debug: var=result

