--- # The wait for Module
- hosts: apacheserver
  sudo: yes
  user: deep
  gather_facts: no
  tasks:
  - name: Installing apche tomcat
    action: apt name=tomcat state=installed
  - name: waiting for port 8080 to listen
    wait_for:
      port: 8080
      state: started
  - name: Installing lynx on apacheserver
    apt: pkg=lynx state=latest

