--- #master playbook for web servers
- hosts: '{{ host_name }}'
  sudo: yes
  user: '{{ user_name }}'
  connection: ssh
  pre_tasks:
  - name: When did the role start
    raw: date > /home/deep/startofrole.log
  roles:
  - { role: '{{ role_name }}', when: "ansible_os_family == 'Debian'" }
  post_tasks:
  - name: When did the role end
    raw: date > /home/deep/endofrole.log

