--- # master role file for testrole
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: date/time stamp for when the playbook start
    command: /bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  roles:
  - testrole
  post_tasks:
  - name: date/time stamp for when the playbook ends
    command: /bin/date
    register: timestamp_end
  - debug: var=timestamp_end


