--- #Outline to playbook Translation
- hosts: apacheserver
  user: deep
  sudo: yes
  gather_facts: no
  tasks:
  - name: date/time stamp for when the playbook start
    command: /bin/date 
    register: timestamp_start
  - debug: var=timestamp_start
  - name: install apache web server
    apt: pkg=apache2 state=latest
    notify: start apache2
  #- name: verify that the web service is running
   # command: systemctl status apache2 
    #register: result
  #- debug: var=result
  - name: install client software
    apt: pkg=telnet state=latest
    apt: pkg=lynx state=latest
  - name:  log all the packages install on the system
    command: apt list --installed
    register: installed_result
  - debug: var=installed_result
  - name: date/time stamp for when the playbook ends
    command: /bin/date
    register: timestamp_end
  - debug: var=timestamp_end  
  handlers:
  - name: start apache2
    service: name=apache2 state=restarted
