--- # apt_repo module exercise
- hosts: apacheserver
  sudo: yes
  user: deep
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Installing a python-apt package
    apt: pkg=python-apt state=latest
  - name: Adding a key
    apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  - name: Adding a repository
    apt_repository: repo='deb http://dl.google.com/linux/deb stable main non-free' state=present

