--- # at module exercise
- hosts: appserver
  sudo: yes
  user: deep
  connection: ssh
  gather_facts: no
  tasks:
  - name: example of a future command withAT module
    at: command="ls /var/log > /home/deep/at1.log" state=absent

