--- #htpasswd module
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: Installing pathlib package 
    action: apt name=python-passlib state=present
  - name: create a user called test in web authentication file called .htpsswd
    htpasswd: path=/etc/apache2/.htpasswd name=test5 password=test5 state=present 

