--- #the stat module
- hosts: appserver
  sudo: yes
  user: deep
  connection: ssh
  gather_facts: no
  tasks:
  #- name: Test for an arbitary directory path in the remote directory
  - stat: path=/home/deep
    register: p
  - debug: msg="The path exists and is a directory"
    when: p.stat.isdir is defined and p.stat.isdir

