--- #web playbook
- hosts: apacheserver
  user: deep
  sudo: yes
  connection: ssh
  vars_files:
    - variables/variables.yml
  tasks:
    - include: packages/packages.yml
    - include: commands/commands.yml
    - include: handler/handler.yml
